-- Disposable CI baseline for bakery storefront contract tests.
-- This is NOT a production migration and intentionally models only the tables/columns
-- required by the bakery checkout migrations.
create extension if not exists pgcrypto;
create schema if not exists auth;
create table if not exists auth.users(id uuid primary key default gen_random_uuid(), email text);
create or replace function auth.uid() returns uuid language sql stable as 'select null::uuid';

create table public.tenants(
 id uuid primary key default gen_random_uuid(), slug text not null unique,
 vertical_id text not null, status text not null default 'demo'
);
create table public.product_categories(
 id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade,
 slug text not null, name text not null, position integer not null default 0, is_active boolean not null default true,
 updated_at timestamptz not null default now(), unique(tenant_id,slug)
);
create table public.products(
 id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade,
 category_id uuid references public.product_categories(id), slug text not null, name text not null,
 description text, short_description text, sku text, base_price numeric not null, currency text not null default 'BRL',
 status text not null default 'active', availability jsonb not null default '{"available":true}'::jsonb,
 metadata jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now(), unique(tenant_id,slug)
);
create table public.coupons(
 id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade,
 code text not null, discount_type text not null, value numeric not null, minimum_subtotal numeric not null default 0,
 maximum_discount numeric, is_active boolean not null default true, starts_at timestamptz, ends_at timestamptz,
 metadata jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now()
);
create unique index coupons_tenant_code_uidx on public.coupons(tenant_id,lower(code));
create table public.orders(
 id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade,
 order_number bigint generated by default as identity, status text not null, fulfillment_type text not null,
 currency text not null, subtotal numeric not null, discount_total numeric not null default 0, delivery_fee numeric not null default 0,
 total numeric not null, coupon_id uuid references public.coupons(id), customer_snapshot jsonb not null default '{}'::jsonb,
 fulfillment_snapshot jsonb not null default '{}'::jsonb, notes text, source text, idempotency_key text, created_by uuid
);
create unique index orders_tenant_idempotency_uidx on public.orders(tenant_id,idempotency_key) where idempotency_key is not null;
create table public.order_items(
 id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade,
 order_id uuid not null references public.orders(id) on delete cascade, product_id uuid references public.products(id),
 name_snapshot text not null, sku_snapshot text, quantity numeric not null, unit_price numeric not null,
 options_snapshot jsonb not null default '{}'::jsonb, line_total numeric not null
);
insert into public.tenants(slug,vertical_id,status) values('fornalha-demo','bakery','demo');
